language: python
python:
  - 3.8
  - 3.7

install: pip install -U poetry tox-travis

script: tox

before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_PASSWORD

deploy:
  provider: script
  script: poetry publish -v --build
  on:
      tags: true
      python: 3.8
      repo: kiudee/bayes-skopt
      branch: master
